#!/usr/bin/env bash
# Deploy world contracts + courier service to local Sui node.
# Expects the node to be running and accounts funded (run via entrypoint.sh).
set -e

WORKSPACE="/workspace"
WORLD_DIR="$WORKSPACE/world-contracts"
COURIER_DIR="$WORKSPACE/move-contracts/capsuleer_courier_service"
DEPLOY_DIR="$WORKSPACE/deployments/localnet"
ENV_FILE="$WORKSPACE/.env.deploy"

mkdir -p "$DEPLOY_DIR"

# Clean stale publication files from previous chain (force-regenesis changes chain ID)
echo "[deploy] Cleaning stale publication files..."
find "$WORLD_DIR" -name "Pub.localnet.toml" -delete 2>/dev/null || true
find "$COURIER_DIR" -name "Pub.localnet.toml" -delete 2>/dev/null || true

echo "[deploy] Deploying world contracts..."
sui client switch --address ADMIN
cd "$WORLD_DIR/contracts/world"
sui client test-publish --build-env testnet --json 2>/dev/null > "$DEPLOY_DIR/world_package.json"

WORLD_PACKAGE_ID=$(jq -r '.objectChanges[] | select(.type == "published") | .packageId' "$DEPLOY_DIR/world_package.json")
if [ -z "$WORLD_PACKAGE_ID" ] || [ "$WORLD_PACKAGE_ID" = "null" ]; then
  echo "[deploy] ERROR: failed to extract WORLD_PACKAGE_ID" >&2
  echo "[deploy] Raw output:" >&2
  head -20 "$DEPLOY_DIR/world_package.json" >&2
  exit 1
fi
echo "[deploy] WORLD_PACKAGE_ID=$WORLD_PACKAGE_ID"

echo "[deploy] Publishing courier service extension..."
cd "$COURIER_DIR"

# Find the publication file generated by world's test-publish
PUB_FILE="$WORLD_DIR/contracts/world/Pub.localnet.toml"
if [ ! -f "$PUB_FILE" ]; then
  # Try alternative location
  PUB_FILE=$(find "$WORLD_DIR" -name "Pub.localnet.toml" -print -quit 2>/dev/null || true)
  if [ -z "$PUB_FILE" ]; then
    echo "[deploy] ERROR: Pub.localnet.toml not found after world deployment" >&2
    find "$WORLD_DIR" -name "Pub.*.toml" -print >&2
    exit 1
  fi
fi
echo "[deploy] Using pubfile: $PUB_FILE"

sui client test-publish --build-env testnet \
  --pubfile-path "$PUB_FILE" \
  --json 2>/dev/null > "$DEPLOY_DIR/courier_package.json"

BUILDER_PACKAGE_ID=$(jq -r '.objectChanges[] | select(.type == "published") | .packageId' "$DEPLOY_DIR/courier_package.json")
EXTENSION_CONFIG_ID=$(jq -r '.objectChanges[] | select(.objectType? // "" | endswith("::config::ExtensionConfig")) | .objectId' "$DEPLOY_DIR/courier_package.json")
ADMIN_CAP_ID=$(jq -r '.objectChanges[] | select(.objectType? // "" | endswith("::config::AdminCap")) | .objectId' "$DEPLOY_DIR/courier_package.json")

for var in BUILDER_PACKAGE_ID EXTENSION_CONFIG_ID ADMIN_CAP_ID; do
  val="${!var}"
  if [ -z "$val" ] || [ "$val" = "null" ]; then
    echo "[deploy] ERROR: failed to extract $var" >&2
    echo "[deploy] Raw output:" >&2
    head -20 "$DEPLOY_DIR/courier_package.json" >&2
    exit 1
  fi
done

cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — contract deployment IDs
WORLD_PACKAGE_ID=$WORLD_PACKAGE_ID
BUILDER_PACKAGE_ID=$BUILDER_PACKAGE_ID
EXTENSION_CONFIG_ID=$EXTENSION_CONFIG_ID
ADMIN_CAP_ID=$ADMIN_CAP_ID
EOF
chmod 600 "$ENV_FILE"

echo ""
echo "================================================"
echo " Contracts deployed successfully"
echo " WORLD_PACKAGE_ID=$WORLD_PACKAGE_ID"
echo " BUILDER_PACKAGE_ID=$BUILDER_PACKAGE_ID"
echo " EXTENSION_CONFIG_ID=$EXTENSION_CONFIG_ID"
echo " ADMIN_CAP_ID=$ADMIN_CAP_ID"
echo " Env file: .env.deploy"
echo "================================================"
