#!/usr/bin/env bash
# Entrypoint: create keys on first run, start local node, fund accounts, drop to shell.
set -e

SUI_CFG="${SUI_CONFIG_DIR:-/root/.sui}"
KEYSTORE="$SUI_CFG/sui.keystore"
CLIENT_YAML="$SUI_CFG/client.yaml"
INIT_MARKER="$SUI_CFG/.initialized"
ENV_FILE="/workspace/.env.sui"

# ---------- first-run: create keys ----------
if [ ! -f "$INIT_MARKER" ]; then
  echo "[sui-dev] First run — initialising keys..."
  mkdir -p "$SUI_CFG"
  printf '%s' '[]' >"$KEYSTORE"
  cat >"$CLIENT_YAML" <<EOF
---
keystore:
  File: $KEYSTORE
envs:
  - alias: localnet
    rpc: "http://127.0.0.1:9000"
  - alias: testnet
    rpc: "https://fullnode.testnet.sui.io"
active_env: localnet
active_address: ~
EOF

  printf 'y\n' | sui client switch --env localnet 2>/dev/null || true

  echo "[sui-dev] Creating keypairs: ADMIN, PLAYER_A, PLAYER_B..."
  for alias in ADMIN PLAYER_A PLAYER_B; do
    printf '\n' | sui client new-address ed25519 "$alias" ||
      {
        echo "[sui-dev] ERROR: failed to create $alias" >&2
        exit 1
      }
  done
  touch "$INIT_MARKER"
  echo "[sui-dev] Keys created."
fi

# ---------- start local node ----------
echo "[sui-dev] Starting local Sui node..."
sui start --with-faucet --force-regenesis &
NODE_PID=$!
trap 'kill "$NODE_PID" 2>/dev/null || true' EXIT

echo "[sui-dev] Waiting for RPC on port 9000..."
for i in $(seq 1 60); do
  curl -s -o /dev/null http://127.0.0.1:9000 2>/dev/null && break
  if [ "$i" -eq 60 ]; then
    echo "[sui-dev] ERROR: RPC did not become ready" >&2
    kill $NODE_PID 2>/dev/null || true
    exit 1
  fi
  sleep 1
done
echo "[sui-dev] RPC responding, waiting for full initialization..."
sleep 5
echo "[sui-dev] Node ready."

# ---------- fund accounts ----------
printf 'y\n' | sui client switch --env localnet 2>/dev/null || true
echo "[sui-dev] Funding accounts from faucet..."
for alias in ADMIN PLAYER_A PLAYER_B; do
  sui client switch --address "$alias"
  for attempt in 1 2 3; do
    sui client faucet 2>&1 && break
    [ "$attempt" -eq 3 ] && {
      echo "[sui-dev] Faucet failed for $alias" >&2
      exit 1
    }
    sleep 2
  done
done
sui client switch --address ADMIN

# ---------- write .env.sui ----------
get_address() { sui keytool export --key-identity "$1" --json 2>/dev/null | jq -r '.key.suiAddress'; }
get_key() { sui keytool export --key-identity "$1" --json 2>/dev/null | jq -r '.exportedPrivateKey'; }

require_val() {
  if [ -z "$2" ] || [ "$2" = "null" ]; then
    echo "[sui-dev] ERROR: failed to export $1" >&2
    exit 1
  fi
}

ADMIN_ADDRESS=$(get_address ADMIN)
PLAYER_A_ADDRESS=$(get_address PLAYER_A)
PLAYER_B_ADDRESS=$(get_address PLAYER_B)
ADMIN_PRIVATE_KEY=$(get_key ADMIN)
PLAYER_A_PRIVATE_KEY=$(get_key PLAYER_A)
PLAYER_B_PRIVATE_KEY=$(get_key PLAYER_B)

for var in ADMIN_ADDRESS PLAYER_A_ADDRESS PLAYER_B_ADDRESS \
  ADMIN_PRIVATE_KEY PLAYER_A_PRIVATE_KEY PLAYER_B_PRIVATE_KEY; do
  require_val "$var" "${!var}"
done

mkdir -p "$(dirname "$ENV_FILE")"
cat >"$ENV_FILE" <<EOF
# Generated by entrypoint.sh — local Sui keys
SUI_NETWORK=localnet
SUI_RPC_URL=http://127.0.0.1:9000
ADMIN_ADDRESS=$ADMIN_ADDRESS
PLAYER_A_ADDRESS=$PLAYER_A_ADDRESS
PLAYER_B_ADDRESS=$PLAYER_B_ADDRESS
ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
PLAYER_A_PRIVATE_KEY=$PLAYER_A_PRIVATE_KEY
PLAYER_B_PRIVATE_KEY=$PLAYER_B_PRIVATE_KEY
EOF
chmod 600 "$ENV_FILE"

# ---------- ready ----------
echo ""
echo "================================================"
echo " Sui dev environment ready"
echo " Local node RPC: http://127.0.0.1:9000"
echo " Keys:           .env.sui"
echo "================================================"
echo ""

exec "${@:-bash}"
