#!/usr/bin/env bash
# Set up a Sui testnet wallet for contract deployment.
# Skips creation if a testnet wallet already exists.
# Saves wallet info to .env.wallet in the workspace.
set -e

WORKSPACE="/workspace"
ENV_FILE="$WORKSPACE/.env.wallet"

# Ensure testnet environment exists.
if ! sui client envs 2>/dev/null | grep -q testnet; then
  echo "[wallet] Adding testnet environment..."
  sui client new-env --alias testnet --rpc https://fullnode.testnet.sui.io:443
fi

sui client switch --env testnet

# Check if we already have an address.
EXISTING=$(sui client active-address 2>/dev/null || true)
if [ -n "$EXISTING" ] && [ "$EXISTING" != "None" ]; then
  echo "[wallet] Testnet wallet already exists: $EXISTING"

  # Export key for the .env file.
  PRIVATE_KEY=$(sui keytool export --key-identity "$EXISTING" --json 2>/dev/null | jq -r '.exportedPrivateKey // empty' || true)

  if [ -n "$PRIVATE_KEY" ]; then
    cat > "$ENV_FILE" <<EOF
# Sui testnet wallet — generated by wallet-setup.sh
SUI_ADDRESS=$EXISTING
SUI_PRIVATE_KEY=$PRIVATE_KEY
EOF
    chmod 600 "$ENV_FILE"
    echo "[wallet] Wallet info saved to .env.wallet"
  else
    echo "[wallet] Could not export private key. You may need to export manually."
  fi

  # Try to faucet anyway in case balance is low.
  echo "[wallet] Requesting faucet tokens..."
  sui client faucet 2>&1 || echo "[wallet] Faucet request failed (may already have tokens)"

  echo ""
  echo "================================================"
  echo " Wallet ready: $EXISTING"
  echo " Environment: testnet"
  echo "================================================"
  exit 0
fi

# Create new address.
echo "[wallet] Creating new testnet wallet..."
OUTPUT=$(sui client new-address ed25519 --json 2>/dev/null)
ADDRESS=$(echo "$OUTPUT" | jq -r '.address // empty')
RECOVERY=$(echo "$OUTPUT" | jq -r '.recoveryPhrase // empty')
PRIVATE_KEY=$(echo "$OUTPUT" | jq -r '.secretKey // empty')

if [ -z "$ADDRESS" ]; then
  echo "[wallet] ERROR: failed to create address" >&2
  echo "$OUTPUT" >&2
  exit 1
fi

# If we didn't get the private key from creation, try export.
if [ -z "$PRIVATE_KEY" ]; then
  PRIVATE_KEY=$(sui keytool export --key-identity "$ADDRESS" --json 2>/dev/null | jq -r '.exportedPrivateKey // empty' || true)
fi

sui client switch --address "$ADDRESS"

cat > "$ENV_FILE" <<EOF
# Sui testnet wallet — generated by wallet-setup.sh
SUI_ADDRESS=$ADDRESS
SUI_PRIVATE_KEY=$PRIVATE_KEY
SUI_RECOVERY_PHRASE=$RECOVERY
EOF
chmod 600 "$ENV_FILE"

echo "[wallet] Requesting faucet tokens..."
sui client faucet 2>&1 || echo "[wallet] Faucet request failed (retry manually)"

echo ""
echo "================================================"
echo " New wallet created: $ADDRESS"
echo " Recovery phrase saved to .env.wallet"
echo " Environment: testnet"
echo "================================================"
